site_name: Wiki
site_description: "A Linux & Cybersecurity notebook forged in fire."
site_author: "Fudomaru"

theme:

  logo: assets/Logo.png

  name: material

  icon: 
    logo: material/brain

    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette: 
    # Palette toggle for light mode
    #- scheme: default
    #toggle:
        #icon: material/lightbulb
        #name: Dark
        #      primary: red
      #      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Light
      primary: teal
      accent: lime
  
  font:
    text: Anonymous Pro
    code: Fira Code
  
  features:
    - navigation.instant 
    - navigation.instant.progress 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer

    - search.suggest

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcel-busch-b42783268

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/fudomaru/wiki
repo_name: ""
edit_uri: ""

nav:

  - Home: index.md
  
  - Projects:
      - EchoSnare: projects/echosnare.md

  - Linux Wizardry:
      - CLI Magic: linux/cli-magic.md
      - System Internals: linux/system-internals.md
      - Network Kung-Fu: linux/networking.md

  - Automation & Scripts:
      - Deploying the Wiki: auto/deploy.md

  - Cybersecurity:
      - Fundamentals: cybersec/fundamentals.md
      - Toolbelt: 
        - nmap: cybersec/toolbelt/nmap.md
      - Playbooks: 
        - Recon: cybersec/playbooks/recon.md

  - CTF & Wargames:
      - Overthewire:
          - Bandit: ctf/overthewire/bandit.md
          - Natas: ctf/overthewire/natas.md
      - HackTheBox: ctf/htb.md
      - TryHackMe: ctf/thm.md

  - Notes:
      - Warboard: notes/warboard.md
      - Certifications: notes/ccna.md
      - Readings & Videos: notes/media.md
      - Projects: 
        - Digital Dojo: notes/projects/digital-dojo.md
        
  - About: about.md
