site_name: Wiki

theme:

  name: material

  icon: 
    logo: material/brain

    admonition:
      note: fontawesome/solid/note-sticky
      info: fontawesome/solid/circle-info

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Dark

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Light
      primary: teal
      accent: light green
  
  font:
    text: Anonymous Pro
    code: Fira Code
  
  features:
    - navigation.instant 
    - navigation.instant.progress 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer

    - search.suggest

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcel-busch-b42783268

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences