site_name: Voidex
site_description: "A Linux & Cybersecurity notebook forged in fire."
site_author: "Fudomaru"

theme:

  name: material

  icon: 
    logo: material/brain

    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Light
      primary: teal
      accent: lime
  
  font:
    text: Anonymous Pro
    code: Fira Code
  
  features:
    - navigation.instant 
    - navigation.instant.progress 
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/marcel-busch-b42783268

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/fudomaru/wiki
repo_name: ""
edit_uri: ""

nav:
  - Home: index.md
  - Foundations:
    - Overview: foundations/overview.md
    - Networking: foundations/networking.md
    - Windows:
      - Overview: foundations/windows/overview.md
      - UEFI: foundations/windows/uefi.md
      - Event Log: foundations/windows/eventviewer.md
      - CLI: foundations/windows/cli-magic.md
    - MacOS: 
      - Overview: foundations/macos/overview.md
    - Linux:
      - Overview: foundations/linux/overview.md
      - CLI: foundations/linux/cli-magic.md
      - System: foundations/linux/system-internals.md
    - Protocols:
      - Overview: foundations/protocols/overview.md
      - SNMP: foundations/protocols/snmp.md
  - Security:
    - Overview: security/overview.md
    - Fundamentals: security/fundamentals.md
    - Pentesting: 
      - Fundamentals: security/pentesting/fundamentals.md
      - Types: security/pentesting/types.md
      - Structure: security/pentesting/structure.md
      - Skills: security/pentesting/skills.md
      - Methodolgies: security/pentesting/methodologies.md
    - Exploits:
      - Overview: security/exploits/overview.md
      - XSS: security/exploits/xss.md
      - Hardcoded Secrets: security/exploits/hardcoded_secrets.md
      - IDOR: security/exploits/idor.md
      - SSRF: security/exploits/ssrf.md
      - SQLI: security/exploits/sqli.md
    - Toolbelt:
      - Overview: security/toolbelt/overview.md
      - Nmap: security/toolbelt/nmap.md
      - Searchsploit: security/toolbelt/searchsploit.md
    - Playbooks:
      - Overview: security/toolbelt/overview.md
      - Recon: security/playbooks/recon.md
      - JS Deobfuscation: security/playbooks/js-deobfuscation.md
  - Homelab:
    - Overview: homelab/overview.md
    - Proxmox: homelab/proxmox.md
    - pfSense: homelab/pfsense.md
    - PiHole: homelab/pihole.md
    - Gitea: homelab/gitea.md
  - Challenges:
    - Overview: challenges/overview.md
    - OverTheWire:
      - Bandit: challenges/overthewire/bandit.md
      - Natas: challenges/overthewire/natas.md
    - HTB: challenges/htb.md
    - THM: 
      - Overview: challenges/thm/overview.md
      - Billing: challenges/thm/billing.md
  - Projects:
    - Overview: projects/overview.md
    - Digital Dojo: projects/digital-dojo.md
    - EchoSnare: projects/echosnare.md
    - Void Linux: projects/void_linux.md
  - Notes:
    - Overview: notes/overview.md
    - CCNA Training: notes/ccna.md
    - Media: notes/media.md
    - Warboard: notes/warboard.md
  - About: about.md

